generator-settings=
op-permission-level=4
allow-nether=true
level-name=world
enable-query=false
allow-flight=true
announce-player-achievements=true
level-type=DEFAULT
enable-rcon=false
force-gamemode=false
level-seed=
server-ip=0.0.0.0
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
snooper-enabled=false
online-mode=false
resource-pack=
pvp=true
difficulty=1
enable-command-block=true
gamemode=0
player-idle-timeout=0
max-players=20
spawn-monsters=true
generate-structures=true
view-distance=6
motd=\u00A76An EaglercraftX server
